name: Build package

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          export TZ=Asia/Shanghai
          sudo apt-get update -q
          sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qttools5-dev-tools -y -q

      - env:
          TG_API: ${{ secrets.TG_API }}
          TG_GROUP_ID: ${{ secrets.TG_GROUP_ID }}
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
            echo "TG_API=${TG_API}" >> $GITHUB_ENV
            echo "TG_GROUP_ID=${TG_GROUP_ID}" >> $GITHUB_ENV

      - name: Build package
        run: |
          python3 maker.py
          rm dist/*
      
#       - name: Push snapshot package
#         uses: "marvinpinto/action-automatic-releases@latest"
#         if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "snapshot"
#           prerelease: false
#           title: "TeamSpeak 3 zh-CN translation snapshot build"
#           files: |
#             Chinese_Translation_zh-CN.ts3_translation
      
      - name: Upload mappings
        uses: actions/upload-artifact@v3
        with:
          name: Chinese_Translation_zh-CN.ts3_translation
          path: Chinese_Translation_zh-CN.ts3_translation
          
      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

      - name: Upload
        run: ossutil cp -f Chinese_Translation_zh-CN.ts3_translation oss://edison-storage/
      
      - name: Group notify
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: python3 maker.py 1
